# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 06:20
from __future__ import unicode_literals

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_categorymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='email',
            field=models.EmailField(default=b'email@email.com', max_length=254, verbose_name=myapp.models.UserModel),
        ),
    ]
